COMMON: &common #基础配置
    DEBUG: True
    TOKEN_KEY: Q77c-x86qI2I9en-rwhYBWHhd575Z25ft-UGQeSqJa0=
    TOKEN_EXPIRE_TIME: 604800 #7 * 24 * 3600
    # 页码设置
    DEFAULT_PAGE_SIZE: 30

    # 数据库连接
    SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://novel:ZrA9w#Rwuw@ddns.pzrpa.com:3306/novel?charset=utf8mb4'
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SQLALCHEMY_POOL_SIZE: 200
    SQLALCHEMY_POOL_RECYCLE: 7200
    SQLALCHEMY_MAX_OVERFLOW: 100
    SQLALCHEMY_POOL_TIMEOUT: 30
    # 日志配置文件路径
    LOGGING_CONFIG_PATH: ./config/logging.yaml
    # 日志文件输出路径
    LOGGING_PATH: ./logs

    # 国际化配置文件路径
    I18N_PATH: ./config/i18n.yaml

    # 任务配置文件路径
    QUEST_PATH: ./static/data/quest.csv

    # redis配置
    REDIS_URL: 'redis://:123456@ddns.pzrpa.com:6379/0'
    CACHE_CONFIG: &cache_config
        CACHE_TYPE: redis
        CACHE_REDIS_URL: 'redis://:123456@ddns.pzrpa.com:6379/0'
        CACHE_DEFAULT_TIMEOUT: 0
        CACHE_THRESHOLD: 0

    # ES配置
    ELASTICSEARCH_URI: {
        'hosts': 'http://anonymous:paizitech@ddns.pzrpa.com:9200/'
    }

DEVELOPMENT: &development
    <<: *common # 继承common，没有重新定义的变量，使用common变量值
    DEBUG: True

PRODUCTION: &production
    <<: *common
    DEBUG: False
    TOKEN_KEY: Q77c-x86qI2I9en-rwhYBWHhd575Z25ft-UGQeSqJa0=

    SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://novel:ZrA9w#Rwuw@ddns.pzrpa.com:3306/novel?charset=utf8mb4'

    REDIS_URL: 'redis://:123456@ddns.pzrpa.com:6379/0'
    CACHE_CONFIG:
        <<: *cache_config
        CACHE_REDIS_URL: 'redis://:123456@ddns.pzrpa.com:6379/0'

    ELASTICSEARCH_URI: {
        'hosts': 'http://anonymous:paizitech@ddns.pzrpa.com:9200/'
    }